on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

name: CI

jobs:
  test:
    name: ${{matrix.os}}-${{matrix.rust}}
    runs-on: ${{matrix.os}}-latest
    strategy:
      fail-fast: false
      matrix:
        rust: [ stable, nightly, 1.70.0 ]
        os: [ ubuntu, macos, windows ]
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{matrix.rust}}
      - run: cargo test

  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt

      - run: cargo fmt --all -- --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@clippy
      - run: cargo clippy --all-features --tests -- -Dclippy::all

  docs:
    name: Docs
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      RUSTDOCFLAGS: "-Dwarnings"
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable

      - name: Check for typos
        uses: crate-ci/typos@master

      - run: cargo doc --all-features --no-deps

  coverage:
    name: Coverage
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: llvm-tools-preview
      - uses: taiki-e/install-action@cargo-llvm-cov

      - run: cargo llvm-cov --all-features --workspace --doctests --html
      - run: cargo llvm-cov report --lcov --output-path ./target/llvm-cov/lcov.info
      - run: cargo llvm-cov report --cobertura --output-path ./target/llvm-cov/lcov.xml
      - run: cargo llvm-cov report --json --output-path ./target/llvm-cov/lcov.json

      - uses: actions/upload-artifact@v4
        with:
          name: test-coverage
          path: ./target/llvm-cov/

  build_example:
    name: Build example
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable

      - name: 'examples/simple'
        run: cargo build --release --package redact-composer --example simple
